# Title

## Problem Set:


## Solution:


In [55]:
# library
import pandas as pd
import numpy as np

from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

Prepare data set

In [34]:
# read csv file
df = pd.read_csv('https://bit.ly/perch_csv') 

# dataframe to numpy array
# Length, Heigth, Thickness
perch_input = df.to_numpy()

# show 10 perch inpit data
print("perch_input: ", perch_input[:10])

# perch target data
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

perch_input:  [[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]]


Split Data Set to train set and test set

In [17]:
# Sata set split to train set and test set 
sli = train_test_split(perch_full, perch_weight, random_state=42)

# train data set
train_input = sli[0]
train_target = sli[2]

# test data set
test_input = sli[1]
test_target = sli[3]

#### Featrue engineering
Practice the PolynomialFeatures function

In [23]:
#Example input data
poly_exam_input = [[2, 3]]

# Declaration
poly = PolynomialFeatures()

# Training
poly.fit(poly_exam_input)

# tranform
poly_exam_train_input = poly.transform(poly_exam_input)

# show tranfromed data
print("poly_exam_train_input: ", poly_exam_train_input)

# Notice: 1 value is bias 
# you can remove bias value as way of below
# PolynomialFeatures(include_bias=False)

poly_exam_train_input:  [[1. 2. 3. 4. 6. 9.]]


Apply to the real data set

In [41]:
# Declaration
poly = PolynomialFeatures(include_bias=False)

# Training
poly.fit(train_input)

# transform
train_poly_input = poly.transform(train_input)
test_poly_input = poly.transform(test_input)

# 42 data, 9 feature 
print("Train Data shape: ", train_poly_input.shape)
# 14 Data, 9 featrues
print("Test  Data shape: ", test_poly_input.shape)

# how to make feature
# x0    
# x0^2  is Square(x0) 
# x0 x1 is x0 * x1
print("Feature_makeing: ", poly.get_feature_names())

Train Data shape:  (42, 9)
Test  Data shape:  (14, 9)
Feature_makeing:  ['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2', 'x2^2']


Multi-full Linear Regression

In [44]:
# Declaration
lr = LinearRegression()

# training
lr.fit(train_poly_input, train_target)

# training score
score_train = lr.score(train_poly_input, train_target)
score_test  = lr.score(test_poly_input, test_target)

# Show score
print("Train Score: ", score_train)
print("Test  Score: ", score_test)

# Difference score
score_differ = score_train - score_test
print("Difference Score: ", score_differ)

Train Score:  0.9903183436982124
Test  Score:  0.9714559911594132
Difference Score:  0.0188623525387992


Add the more  features

In [51]:
# Declaration
# degree is power of numbers  
poly = PolynomialFeatures(degree=5, include_bias=False)

# training
poly.fit(train_input)

# transform
train_poly_input = poly.transform(train_input)
test_poly_input = poly.transform(test_input)

# 42 Data, 55 featrues
print("Train Data shape: ", train_poly_input.shape)
# 14 Data, 55 featrues
print("Test  Data shape: ", test_poly_input.shape)

Train Data shape:  (42, 55)
Test  Data shape:  (14, 55)


####Multi-full Linear Regression
Too many features -> Overffiting

In [54]:
# Declaration
lr = LinearRegression()

# training
lr.fit(train_poly_input, train_target)

# training score
score_train = lr.score(train_poly_input, train_target)
score_test  = lr.score(test_poly_input, test_target)

# Show score
print("Train Score: ", score_train) # oh! perfect socre
print("Test  Score: ", score_test) # but, test Score is -144 !!

# Difference score
score_differ = score_train - score_test
print("Difference Score: ", score_differ) # Overffiting

## Notice: 
# If train_input have too many features,  
# this model trained perfectly fitting  in train data set. 
# so, this model become the 'overffiting' in train data set.

Train Score:  0.9999999999991096
Test  Score:  -144.40579242335605
Difference Score:  145.40579242335517


#### Regularization
protect from 'Overfitting'  
by Standard Scaler

In [58]:
# Declaration
ss = StandardScaler()

# Trainning
ss.fit(train_poly_input)

# Transform
train_scaled_input = ss.transform(train_poly_input)
test_scaled_input = ss.transform(test_poly_input)


