# Title

## Problem Set:


## Solution:


In [38]:
# library
import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# from sklearn.preprocessing import PolynomialFeatures
# from sklearn.linear_model import LinearRegression
# from sklearn.linear_model import Ridge
# from sklearn.linear_model import Lasso

Prepare Data Set

In [5]:
fish = pd.read_csv('https://bit.ly/fish_csv')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

Check kind of fish

In [42]:
# There are 7 kind of fish
kind_fish = pd.unique(fish['Species'])
print(kind_fish)

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


Check columns

In [33]:
col = list(fish.columns)
input_col = col[1:]
target_col = col[:1]

print("Fish input columns  : ", input_col)
print("Fish target columns : ", target_col) # Species

Fish input columns  :  ['Weight', 'Length', 'Diagonal', 'Height', 'Width']
Fish target columns :  ['Species']


Make fish data (input, target)

In [32]:
fish_input  = fish[input_col].to_numpy()
fish_target = fish[target_col].to_numpy()

print("Fish_input 2D Matrix:")
print(fish_input[:5], end="\n\n")

print("Fish_target 2D Matrix:")
print(fish_target[:5])

Fish_input 2D Matrix:
[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]

Fish_target 2D Matrix:
[['Bream']
 ['Bream']
 ['Bream']
 ['Bream']
 ['Bream']]


Divied fish data to train data and test data

In [37]:
sli = train_test_split(fish_input, fish_target, random_state=42)

# Train data Set
train_input = sli[0]
train_target = sli[2]

# Test data Set
test_input = sli[1]
test_target = sli[3]

Standardization

In [43]:
# Declaration
ss = StandardScaler()

# Training
ss.fit(train_input)

# trasform
train_scaled_input = ss.transform(train_input)
test_scaled_input = ss.transform(test_input)